<#
.SYNOPSIS
    Consolidates "Switch*" sheets from a source workbook into a summary sheet.
.DESCRIPTION
    This script reads all worksheets whose names start with "Switch" from a source Excel workbook (generated by Sam Pursglove's Analyze-CiscoSwitchConfiguration script) and builds a consolidated table of results at the start of the source workbook. 
.PARAMETER SourceWorkbookPath
    Path to the source Excel workbook (.xlsx). If omitted the script will prompt for the path.
.PARAMETER Hidden
    If present Excel will run hidden (no visible UI). Default is visible.
.EXAMPLE
    Consolidate-CiscoSwitchConfiguration.ps1 switch_analysis_output.xlsx 

    Generates a summary worksheet of the Cisco switch configuration analysis results produced by the Analyze-CiscoSwitchConfiguration.ps1 script.
.NOTES
    Version 1.01
    Olivia Tierney
#>

param(
    [Parameter(Position=0, HelpMessage = "Path to the source Excel workbook (.xlsx)")]
    [string]$SourceWorkbookPath,

    [Parameter(HelpMessage = "Run Excel hidden (no visible UI)")]
    [switch]$Hidden
)



function Get-OleColor {
    param([int]$R, [int]$G, [int]$B)
    return $R + ($G -shl 8) + ($B -shl 16)
}


function Get-DefaultTestDefinitions {
    
    # Define test structure
    $TestDefinitions = [ordered]@{
        'General' = [ordered]@{
            'Cisco IOS version 15 or newer' = 'N/A'
            'Login failure logging' = 'N/A'
            'Login/MOTD banner' = 'N/A'
            'Enable password encryption type(s)' = 'N/A'
            'User password encryption type(s)' = 'N/A'
            'Local accounts and encryption' = 'N/A'
            'Enable secret/password' = 'N/A'
            'Service password encryption' = 'N/A'
            'Login success logging' = 'N/A'
        }
        'Server' = [ordered]@{
            'Redundant NTP servers' = 'N/A'
            'Syslog server(s)' = 'N/A'
            'TFTP server' = 'N/A'
            'HTTP web management server' = 'N/A'
        }
        'AAA' = [ordered]@{
            'Authentication, Authorization, Accounting' = 'N/A'
            'Global login authentication' = 'N/A'
            'Global enable authentication' = 'N/A'
            '802.1X authentication server' = 'N/A'
        }
        'SSH' = [ordered]@{
            'Version' = 'N/A'
            'Authentication retries' = 'N/A'
            'Authentication timeout' = 'N/A'
        }
        'SNMP' = [ordered]@{
            'v2 Read-Only (RO) community strings' = 'N/A'
            'v2 Read-Write (RW) community strings' = 'N/A'
            'v3 Group(s) configured for authPriv' = 'N/A'
        }
        'NTP' = [ordered]@{
            'NTP authentication' = 'N/A'
            'NTP logging' = 'N/A'
        }
        'Interfaces' = [ordered]@{
            'Access ports using VLAN 1' = 'N/A'
            'Dynamic ports using VLAN 1' = 'N/A'
            'Shutdown ports in VLAN 1' = 'N/A'
            'Port security multiple MAC addresses' = 'N/A'
            'Sticky port port-security' = 'N/A'
            'Trunking native VLAN' = 'N/A'
            'Access and trunk settings' = 'N/A'
            'Configured for full duplex' = 'N/A'
            'Configured for half duplex' = 'N/A'
            'With BPDUGuard and BPDUFilter' = 'N/A'
        }
        'VLAN1' = [ordered]@{
            'IP address' = 'N/A'
            'VLAN1 state' = 'N/A'
        }
        'Console' = [ordered]@{
            'Logging synchronous' = 'N/A'
            'Timeout' = 'N/A'
            'Login method' = 'N/A'
            'Transport output' = 'N/A'
            'Transport preferred' = 'N/A'
        }
        'VTY 0-4' = [ordered]@{
            'Logging synchronous' = 'N/A'
            'Timeout' = 'N/A'
            'Login method' = 'N/A'
            'Remote access' = 'N/A'
            'Transport input' = 'N/A'
            'Transport output' = 'N/A'
            'Transport preferred' = 'N/A'
        }
        'VTY 5-15' = [ordered]@{
            'Logging synchronous' = 'N/A'
            'Timeout' = 'N/A'
            'Login method' = 'N/A'
            'Remote access' = 'N/A'
            'Transport input' = 'N/A'
            'Transport output' = 'N/A'
            'Transport preferred' = 'N/A'
        }
        'VTY 16-31' = [ordered]@{
            'Logging synchronous' = 'N/A'
            'Timeout' = 'N/A'
            'Login method' = 'N/A'
            'Remote access' = 'N/A'
            'Transport input' = 'N/A'
            'Transport output' = 'N/A'
            'Transport preferred' = 'N/A'
        }
    }

    return $TestDefinitions
}

# Input Parameter 1: $SourceWorkbook is an Excel Workbook Object 
# Returns - Array List Object of a Cisco Switch Names dervived from Spreadsheet tabs
function Get-SwitchSheets{
    # Collect switch sheets (exclude only the newly created consolidated sheet)
    param([Parameter(Mandatory)]$SourceWorkbook)
    $switchSheets= @()
    foreach ($worksheet in $sourceWorkbook.Worksheets) {
        if ($worksheet.Name -notlike "General Info" -and $worksheet.Name -notlike "Consolidated Results")
        {
            $switchSheets += $worksheet
        }
    }

    # Check if no Switch Sheets were found
    if ($SwitchSheets.Count -eq 0) {
        Write-Host "No switch sheets found in workbook!" -ForegroundColor Red
        throw "No switch sheets found. Cannot build consolidated data structure."
    }

    return $switchSheets
}

# Input Parameter 1: $SwitchSheets is an Array Object 
# Returns - Dictionary List Object of a Default Cisco Switch Test Output
function Build-ConsolidatedOutputStructure{
    # Parses each Switch Sheet
    param([Parameter(Mandatory)]$SwitchSheets)

    $OutputStructure = [ordered]@{}
    
    foreach ($sheet in $SwitchSheets) {
        $OutputStructure[$sheet.Name] = Get-DefaultTestDefinitions

        # Get the last row with data in this sheet
        $lastRow = $sheet.UsedRange.Rows.Count

        # Loop through each row (starting at row 2 to skip header)
        for ($row = 2; $row -le $lastRow; $row++) {
            # Read the cells
            $category = $sheet.Cells.Item($row, 1).Text      # Column A: Category
            $description = $sheet.Cells.Item($row, 2).Text   # Column B: Description
            $state = $sheet.Cells.Item($row, 3).Text         # Column C: State
            
            # Skip if category or description is empty
            if ([string]::IsNullOrWhiteSpace($category) -or [string]::IsNullOrWhiteSpace($description)) {
                Write-Host "Category or Description is Null. Skipping."
                continue
            }
            # Check if this category exists in our structure
            if ($OutputStructure[$sheet.Name].Contains($category)) {
                # Check if this test exists in the category
                if ($OutputStructure[$sheet.Name][$category].Contains($description)) {
                    # Update the state from N/A to actual value
                    $OutputStructure[$sheet.Name][$category][$description] = $state
                }
            }
        }
    }

    return $OutputStructure
}

# Input Parameter 1: $OutputStructure is a Dictionary List Object 
function Create-ConsolidatedSpreadSheet{
    # Parses each Switch Sheet
    param(
    [Parameter(Mandatory=$true)]
        $OutputStructure,

    [Parameter(Mandatory=$true)]
        $SourceWorkbook)

    $newSheet = $SourceWorkbook.Worksheets.Item(1)
    $destSheet = $sourceWorkbook.Worksheets.Add($newSheet)
    
    # Name the new sheet "Consolidated Results" (make unique if necessary)
    $baseName = "Consolidated Results"
    $destName = $baseName
    $suffix = 1
    while ($true) {
        $exists = $null
        try {
            $exists = $sourceWorkbook.Worksheets.Item($destName)
        } catch {
            $exists = $null
        }
        if ($exists -ne $null -and $exists -ne $destSheet) {
            $destName = "$baseName ($suffix)"
            $suffix++
        } else {
            break
        }
    }

    try {
        $destSheet.Name = $destName
    } catch {
        Write-Warning "Unable to set destination sheet name to '$destName'. Using default name."
    }
    
    Write-Host "Creating Consolidated Results sheet..." -ForegroundColor Cyan

    # Get all switches (sorted)
    $switches = $OutputStructure.Keys | Sort-Object
    
    # ROW 1: Write "Switches" header spanning all switch columns
    $destSheet.Cells.Item(1, 2).Value2 = "Switches"
    $destSheet.Cells.Item(1, 2).Font.Bold = $true
    $destSheet.Cells.Item(1, 2).HorizontalAlignment = -4108  # xlCenter
    $destSheet.Cells.Item(1, 2).Interior.ColorIndex = 15
    
    # Merge "Switches" across all switch columns
    $lastCol = $switches.Count + 1
    $switchHeaderRange = $destSheet.Range(
        $destSheet.Cells.Item(1, 2),
        $destSheet.Cells.Item(1, $lastCol)
    )
    $switchHeaderRange.Merge() | Out-Null
    
    # ROW 2: Write "Test" label and individual switch names
    $destSheet.Cells.Item(2, 1).Value2 = "Test"
    $destSheet.Cells.Item(2, 1).Font.Bold = $true
    $destSheet.Cells.Item(2, 1).Interior.ColorIndex = 15
    
    # Write switch names as column headers
    $col = 2
    foreach ($switch in $switches) {
        $destSheet.Cells.Item(2, $col).Value2 = $switch
        $destSheet.Cells.Item(2, $col).Font.Bold = $true
        $destSheet.Cells.Item(2, $col).Interior.ColorIndex = 15
        $col++
    }
    
    # Get all categories from first switch
    $firstSwitch = $switches[0]
    $categories = $OutputStructure[$firstSwitch].Keys
    
    $currentRow = 3  # Start at row 3 now (after two header rows)
    
    # Process each category
    foreach ($category in $categories) {
        # Write category header row
        $destSheet.Cells.Item($currentRow, 1).Value2 = $category
        $destSheet.Cells.Item($currentRow, 1).Font.Bold = $true
        $destSheet.Cells.Item($currentRow, 1).Font.Italic = $true
        $destSheet.Cells.Item($currentRow, 1).Interior.Color = 12632256  # Light blue
        
        # Merge cells across all switch columns for category header
        $range = $destSheet.Range(
            $destSheet.Cells.Item($currentRow, 1),
            $destSheet.Cells.Item($currentRow, $lastCol)
        )
        $range.Merge() | Out-Null
        $currentRow++
        
        # Get all test names for this category
        $testNames = @()
        foreach ($switch in $switches) {
            if ($OutputStructure[$switch].Contains($category)) {
                $testNames += $OutputStructure[$switch][$category].Keys
            }
        }
        $testNames = $testNames | Select-Object -Unique
        
        # Write each test as a row
        foreach ($testName in $testNames) {
            # Write test name
            $destSheet.Cells.Item($currentRow, 1).Value2 = $testName
            
            # Write results for each switch
            $col = 2
            foreach ($switch in $switches) {
                $value = ""
                if ($OutputStructure[$switch].Contains($category) -and 
                    $OutputStructure[$switch][$category].Contains($testName)) {
                    $value = $OutputStructure[$switch][$category][$testName]
                }
                
                $cell = $destSheet.Cells.Item($currentRow, $col)
                $cell.Value2 = $value
                
                # Apply color coding
                switch ($value) {
                    "Pass"    { $cell.Interior.Color = 5296274 }   # Light green
                    "Fail"    { $cell.Interior.Color = 13551615 }  # Light red
                    "Warning" { $cell.Interior.Color = 10092543 }  # Light orange
                    "Notice"  { $cell.Interior.Color = 16777164 }  # Light yellow
                    "N/A"     { $cell.Interior.ColorIndex = 15 }   # Gray
                }
                
                $col++
            }
            $currentRow++
        }
        
        # Add blank row between categories
        $currentRow++
    }
    
    # Format the sheet
    $destSheet.Columns.AutoFit() | Out-Null
    
    # Freeze top two rows
    $destSheet.Application.ActiveWindow.SplitRow = 2
    $destSheet.Application.ActiveWindow.FreezePanes = $true
    
    Write-Host "Consolidated Results sheet created successfully!" -ForegroundColor Green
}

###                      ###
###      BEGIN MAIN      ###
###                      ###

$ErrorActionPreference = 'Stop'

if (-not $SourceWorkbookPath) {
    $SourceWorkbookPath = Read-Host "Enter the full path to the source workbook (or drag the file here and press Enter)"
    if (-not $SourceWorkbookPath) {
        Write-Error "No source workbook path provided. Exiting."
        return
    }
}

try {
    $resolved = Resolve-Path -Path $SourceWorkbookPath -ErrorAction Stop
    $SourceWorkbookPath = $resolved.Path
} catch {
    Write-Error "Source workbook not found: $SourceWorkbookPath"
    return
}


try {

    # Open Hidden 
    $excel = New-Object -ComObject Excel.Application
    $excel.Visible = -not $Hidden.IsPresent
    #$excel.Visible = $false
    $excel.DisplayAlerts = $false
    $sourceWorkbook = $excel.Workbooks.Open($SourceWorkbookPath)
    
    $switchSheets = Get-SwitchSheets -SourceWorkbook $sourceWorkbook
    $outputStructure = Build-ConsolidatedOutputStructure -SwitchSheets $switchSheets
    Create-ConsolidatedSpreadSheet -OutputStructure $outputStructure -SourceWorkbook $sourceWorkbook

    # Close Excel 
    if (-not $excel.Visible) 
    {
        $sourceWorkbook.Close($false)
        $excel.Quit()
    }

} catch {
    # If We Encounter an Error close the Sheet without saving.
    Write-Error "An error occurred: $_"
    Write-Error $_.Exception.Message
    if ($sourceWorkbook) {
        try { $sourceWorkbook.Close($false) } catch {}
    }
    if ($excel) {
        try { $excel.Quit() } catch {}
    }
} finally {
    # Release COM objects
    if ($destSheet) {
        try { [System.Runtime.Interopservices.Marshal]::ReleaseComObject($destSheet) | Out-Null } catch {}
        $destSheet = $null
    }
    if ($sourceWorkbook) {
        try { [System.Runtime.Interopservices.Marshal]::ReleaseComObject($sourceWorkbook) | Out-Null } catch {}
        $sourceWorkbook = $null
    }
    if ($excel) {
        try { [System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null } catch {}
        $excel = $null
    }
    [GC]::Collect()
    [GC]::WaitForPendingFinalizers()
}